# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KeyValueClusterStore.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='KeyValueClusterStore.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1aKeyValueClusterStore.proto\"t\n\x0fSetupConnection\x12.\n\x0c\x61ll_clusters\x18\x02 \x03(\x0b\x32\x18.SetupConnection.Cluster\x1a\x31\n\x07\x43luster\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\"*\n\rStartElection\x12\x0b\n\x03src\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\r\"X\n\x0bRequestVote\x12\x0c\n\x04term\x18\x01 \x01(\r\x12\x13\n\x0b\x63lusterName\x18\x02 \x01(\t\x12\x11\n\tclusterIp\x18\x03 \x01(\t\x12\x13\n\x0b\x63lusterPort\x18\x04 \x01(\r\"E\n\x0cResponseVote\x12\x0c\n\x04term\x18\x01 \x01(\r\x12\x12\n\nvoteStatus\x18\x02 \x01(\t\x12\x13\n\x0b\x63lusterName\x18\x03 \x01(\t\"5\n\x10HeartBeatMessage\x12\x0c\n\x04term\x18\x01 \x01(\r\x12\x13\n\x0b\x63lusterName\x18\x02 \x01(\t\"\xfc\x01\n\x0fKeyValueMessage\x12,\n\x10setup_connection\x18\x01 \x01(\x0b\x32\x10.SetupConnectionH\x00\x12(\n\x0estart_election\x18\x02 \x01(\x0b\x32\x0e.StartElectionH\x00\x12$\n\x0crequest_vote\x18\x03 \x01(\x0b\x32\x0c.RequestVoteH\x00\x12&\n\rresponse_vote\x18\x04 \x01(\x0b\x32\r.ResponseVoteH\x00\x12.\n\x11heartbeat_message\x18\x05 \x01(\x0b\x32\x11.HeartBeatMessageH\x00\x42\x13\n\x11key_value_messageb\x06proto3')
)




_SETUPCONNECTION_CLUSTER = _descriptor.Descriptor(
  name='Cluster',
  full_name='SetupConnection.Cluster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SetupConnection.Cluster.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='SetupConnection.Cluster.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='SetupConnection.Cluster.port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=146,
)

_SETUPCONNECTION = _descriptor.Descriptor(
  name='SetupConnection',
  full_name='SetupConnection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='all_clusters', full_name='SetupConnection.all_clusters', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SETUPCONNECTION_CLUSTER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=146,
)


_STARTELECTION = _descriptor.Descriptor(
  name='StartElection',
  full_name='StartElection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='StartElection.src', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='term', full_name='StartElection.term', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=190,
)


_REQUESTVOTE = _descriptor.Descriptor(
  name='RequestVote',
  full_name='RequestVote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='RequestVote.term', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clusterName', full_name='RequestVote.clusterName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clusterIp', full_name='RequestVote.clusterIp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clusterPort', full_name='RequestVote.clusterPort', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=280,
)


_RESPONSEVOTE = _descriptor.Descriptor(
  name='ResponseVote',
  full_name='ResponseVote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='ResponseVote.term', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voteStatus', full_name='ResponseVote.voteStatus', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clusterName', full_name='ResponseVote.clusterName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=351,
)


_HEARTBEATMESSAGE = _descriptor.Descriptor(
  name='HeartBeatMessage',
  full_name='HeartBeatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='HeartBeatMessage.term', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clusterName', full_name='HeartBeatMessage.clusterName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=406,
)


_KEYVALUEMESSAGE = _descriptor.Descriptor(
  name='KeyValueMessage',
  full_name='KeyValueMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setup_connection', full_name='KeyValueMessage.setup_connection', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_election', full_name='KeyValueMessage.start_election', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_vote', full_name='KeyValueMessage.request_vote', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_vote', full_name='KeyValueMessage.response_vote', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heartbeat_message', full_name='KeyValueMessage.heartbeat_message', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='key_value_message', full_name='KeyValueMessage.key_value_message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=409,
  serialized_end=661,
)

_SETUPCONNECTION_CLUSTER.containing_type = _SETUPCONNECTION
_SETUPCONNECTION.fields_by_name['all_clusters'].message_type = _SETUPCONNECTION_CLUSTER
_KEYVALUEMESSAGE.fields_by_name['setup_connection'].message_type = _SETUPCONNECTION
_KEYVALUEMESSAGE.fields_by_name['start_election'].message_type = _STARTELECTION
_KEYVALUEMESSAGE.fields_by_name['request_vote'].message_type = _REQUESTVOTE
_KEYVALUEMESSAGE.fields_by_name['response_vote'].message_type = _RESPONSEVOTE
_KEYVALUEMESSAGE.fields_by_name['heartbeat_message'].message_type = _HEARTBEATMESSAGE
_KEYVALUEMESSAGE.oneofs_by_name['key_value_message'].fields.append(
  _KEYVALUEMESSAGE.fields_by_name['setup_connection'])
_KEYVALUEMESSAGE.fields_by_name['setup_connection'].containing_oneof = _KEYVALUEMESSAGE.oneofs_by_name['key_value_message']
_KEYVALUEMESSAGE.oneofs_by_name['key_value_message'].fields.append(
  _KEYVALUEMESSAGE.fields_by_name['start_election'])
_KEYVALUEMESSAGE.fields_by_name['start_election'].containing_oneof = _KEYVALUEMESSAGE.oneofs_by_name['key_value_message']
_KEYVALUEMESSAGE.oneofs_by_name['key_value_message'].fields.append(
  _KEYVALUEMESSAGE.fields_by_name['request_vote'])
_KEYVALUEMESSAGE.fields_by_name['request_vote'].containing_oneof = _KEYVALUEMESSAGE.oneofs_by_name['key_value_message']
_KEYVALUEMESSAGE.oneofs_by_name['key_value_message'].fields.append(
  _KEYVALUEMESSAGE.fields_by_name['response_vote'])
_KEYVALUEMESSAGE.fields_by_name['response_vote'].containing_oneof = _KEYVALUEMESSAGE.oneofs_by_name['key_value_message']
_KEYVALUEMESSAGE.oneofs_by_name['key_value_message'].fields.append(
  _KEYVALUEMESSAGE.fields_by_name['heartbeat_message'])
_KEYVALUEMESSAGE.fields_by_name['heartbeat_message'].containing_oneof = _KEYVALUEMESSAGE.oneofs_by_name['key_value_message']
DESCRIPTOR.message_types_by_name['SetupConnection'] = _SETUPCONNECTION
DESCRIPTOR.message_types_by_name['StartElection'] = _STARTELECTION
DESCRIPTOR.message_types_by_name['RequestVote'] = _REQUESTVOTE
DESCRIPTOR.message_types_by_name['ResponseVote'] = _RESPONSEVOTE
DESCRIPTOR.message_types_by_name['HeartBeatMessage'] = _HEARTBEATMESSAGE
DESCRIPTOR.message_types_by_name['KeyValueMessage'] = _KEYVALUEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetupConnection = _reflection.GeneratedProtocolMessageType('SetupConnection', (_message.Message,), dict(

  Cluster = _reflection.GeneratedProtocolMessageType('Cluster', (_message.Message,), dict(
    DESCRIPTOR = _SETUPCONNECTION_CLUSTER,
    __module__ = 'KeyValueClusterStore_pb2'
    # @@protoc_insertion_point(class_scope:SetupConnection.Cluster)
    ))
  ,
  DESCRIPTOR = _SETUPCONNECTION,
  __module__ = 'KeyValueClusterStore_pb2'
  # @@protoc_insertion_point(class_scope:SetupConnection)
  ))
_sym_db.RegisterMessage(SetupConnection)
_sym_db.RegisterMessage(SetupConnection.Cluster)

StartElection = _reflection.GeneratedProtocolMessageType('StartElection', (_message.Message,), dict(
  DESCRIPTOR = _STARTELECTION,
  __module__ = 'KeyValueClusterStore_pb2'
  # @@protoc_insertion_point(class_scope:StartElection)
  ))
_sym_db.RegisterMessage(StartElection)

RequestVote = _reflection.GeneratedProtocolMessageType('RequestVote', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTVOTE,
  __module__ = 'KeyValueClusterStore_pb2'
  # @@protoc_insertion_point(class_scope:RequestVote)
  ))
_sym_db.RegisterMessage(RequestVote)

ResponseVote = _reflection.GeneratedProtocolMessageType('ResponseVote', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEVOTE,
  __module__ = 'KeyValueClusterStore_pb2'
  # @@protoc_insertion_point(class_scope:ResponseVote)
  ))
_sym_db.RegisterMessage(ResponseVote)

HeartBeatMessage = _reflection.GeneratedProtocolMessageType('HeartBeatMessage', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEATMESSAGE,
  __module__ = 'KeyValueClusterStore_pb2'
  # @@protoc_insertion_point(class_scope:HeartBeatMessage)
  ))
_sym_db.RegisterMessage(HeartBeatMessage)

KeyValueMessage = _reflection.GeneratedProtocolMessageType('KeyValueMessage', (_message.Message,), dict(
  DESCRIPTOR = _KEYVALUEMESSAGE,
  __module__ = 'KeyValueClusterStore_pb2'
  # @@protoc_insertion_point(class_scope:KeyValueMessage)
  ))
_sym_db.RegisterMessage(KeyValueMessage)


# @@protoc_insertion_point(module_scope)
